version: 2.1

workflows:
  build-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master # Only run deploy job when commit is on the main branch

jobs:
  #  build and test jobs go here - not included for brevity
  deploy-job:
    docker:
      - image: cimg/ruby:3.0.4
    steps:
      - add_ssh_keys:
          fingerprints:
            - "25:28:f1:78:21:d0:b8:8f:97:0f:e2:9d:4f:e1:f9:a3"
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploy if tests pass and branch is Main
          command: bundle exec cap staging deploy
